#!/bin/bash

# https://www.it-dan.com/blog/block-ads-linux-and-bind9
# http://someonewhocares.org/hosts/zero/
# https://ewpratten.github.io/youtube_ad_blocklist/hosts.ipv4.txt

TMP=$(mktemp)
ZONES="/etc/bind/zones.blocked"
WHITELIST="analytics\.google\.com|crackstation\.net"
URLS=(
    https://someonewhocares.org/hosts/zero/hosts
    https://ewpratten.github.io/youtube_ad_blocklist/hosts.ipv4.txt
    https://raw.githubusercontent.com/zessu/pi-hole-dns/master/list1.txt
    https://raw.githubusercontent.com/zessu/pi-hole-dns/master/list2.txt
    https://raw.githubusercontent.com/trippz/adult-block-list/master/hosts.txt
    https://raw.githubusercontent.com/kboghdady/youTube_ads_4_pi-hole/master/black.list
)

readonly TMP ZONES WHITELIST URLS

# Put all URLS into TMP
for url in "${URLS[@]}"; do
  wget -O - "$url" --quiet | \
    grep -Po '^(?:0.0.0.0 )?((?:[a-z0-9\-]+\.)+[a-z\-]+)(?:$| )' | \
    awk '{print $NF}' | tr "[:upper:]" "[:lower:]" >> "$TMP"
done

# Ensure only unique entries are added to zones file
sort -u "$TMP" | grep -v -P $WHITELIST | \
  awk '{ print "zone \""$1"\" { type master; notify no; file \"/etc/bind/blocked.zone\"; };" }' \
  > $ZONES

wget -O - "https://raw.githubusercontent.com/royarisse/bind-sinkhole/master/zones.ads" --quiet > /etc/bind/zones.ads
wget -O - "https://raw.githubusercontent.com/royarisse/bind-sinkhole/master/zones.distracting" --quiet > /etc/bind/zones.distracting

if named-checkconf; then
  rndc reload > /dev/null
fi
