#!/bin/bash

# https://www.it-dan.com/blog/block-ads-linux-and-bind9
# http://someonewhocares.org/hosts/zero/
# https://ewpratten.github.io/youtube_ad_blocklist/hosts.ipv4.txt

TMP=$(mktemp)
ZONES="/etc/bind/zones.blocked"
WHITELIST="/etc/bind/hosts.allow"
BLACKLIST="/etc/bind/hosts.block"
URLS=(
    https://someonewhocares.org/hosts/zero/hosts
    https://ewpratten.github.io/youtube_ad_blocklist/hosts.ipv4.txt
    https://raw.githubusercontent.com/zessu/pi-hole-dns/master/list1.txt
    https://raw.githubusercontent.com/zessu/pi-hole-dns/master/list2.txt
    https://raw.githubusercontent.com/trippz/adult-block-list/master/hosts.txt
    https://raw.githubusercontent.com/kboghdady/youTube_ads_4_pi-hole/master/black.list
)

readonly TMP ZONES WHITELIST BLACKLIST URLS

# Put all URLS into TMP
for url in "${URLS[@]}"; do
  wget -O - "$url" --quiet | \
    grep -Po '^(?:0.0.0.0 )?((?:[a-z0-9\-]+\.)+[a-z\-]+)(?:$| )' | \
    awk '{print $NF}' | tr "[:upper:]" "[:lower:]" >> "$TMP"
done

# Add manually blacklisted too
sort -u "$BLACKLIST" >> "$TMP"

# Get unique lines and add to zones file
sort -u "$TMP" | while IFS= read -r HOSTNAME; do
  # Skip empty lines and comments
  if [[ -z "$HOSTNAME" || "$HOSTNAME" =~ ^# ]]; then
    continue
  fi

  # Skip whitelisted HOSTNAMEs
  if grep -q -i "^$HOSTNAME$" "$WHITELIST"; then
    continue
  fi

  # Add HOSTNAME to zones file
  awk '{ print "zone \""$1"\" { type master; notify no; file \"/etc/bind/blocked.zone\"; };" }' \
    > $ZONES
done

if named-checkconf; then
  rndc reload > /dev/null
fi
